name: serena

services:
  serena:
    image: ghcr.io/oraios/serena:latest 
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    environment:
      - SERENA_DOCKER=1
    networks:
      - shared_net
    expose:
      - "9121"  # MCP server port
      - "24282"  # Dashboard port
    volumes:
      - /opt/docker:/opt/docker
      - /mnt/backblaze:/mnt/backblaze
    command:
      - "uv run --directory /workspaces/serena serena-mcp-server --transport stdio"
    stdin_open: true
    tty: true

networks:
  shared_net:
    external: true